#!/usr/bin/env bash
# installs nginx and configures it on a remote server

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
service nginx restart

# Check if Nginx is installed and configured correctly
curl -s localhost | grep "Hello World!" > /dev/null

if [ $? -eq 0 ]; then
    echo "Nginx is installed and serving the correct content."
else
    echo "Nginx installation or configuration failed."
    exit 1
fi
